DECLARE @OFI VARCHAR(8)
SET @OFI = '00009507' 

DECLARE @T0 VARCHAR(5), @T1 VARCHAR(5), @T2 VARCHAR(5), @T3 VARCHAR(5), @T4 VARCHAR(5), @T5 VARCHAR(5), @T6 VARCHAR(5), @T7 VARCHAR(5), @T8 VARCHAR(5), @T9 VARCHAR(5)

SET @T0 = (SELECT top 1 T0 FROM [PO-DETA] PD INNER JOIN POS PP ON PP.PO = PD.PO where ofi = @OFI)
SET @T1 = (SELECT top 1 T1 FROM [PO-DETA] PD INNER JOIN POS PP ON PP.PO = PD.PO where ofi = @OFI)
SET @T2 = (SELECT top 1 T2 FROM [PO-DETA] PD INNER JOIN POS PP ON PP.PO = PD.PO where ofi = @OFI)
SET @T3 = (SELECT top 1 T3 FROM [PO-DETA] PD INNER JOIN POS PP ON PP.PO = PD.PO where ofi = @OFI)
SET @T4 = (SELECT top 1 T4 FROM [PO-DETA] PD INNER JOIN POS PP ON PP.PO = PD.PO where ofi = @OFI)
SET @T5 = (SELECT top 1 T5 FROM [PO-DETA] PD INNER JOIN POS PP ON PP.PO = PD.PO where ofi = @OFI)
SET @T6 = (SELECT top 1 T6 FROM [PO-DETA] PD INNER JOIN POS PP ON PP.PO = PD.PO where ofi = @OFI)
SET @T7 = (SELECT top 1 T7 FROM [PO-DETA] PD INNER JOIN POS PP ON PP.PO = PD.PO where ofi = @OFI)
SET @T8 = (SELECT top 1 T8 FROM [PO-DETA] PD INNER JOIN POS PP ON PP.PO = PD.PO where ofi = @OFI)
SET @T9 = (SELECT top 1 T9 FROM [PO-DETA] PD INNER JOIN POS PP ON PP.PO = PD.PO where ofi = @OFI)

 EXEC('SELECT DISTINCT et.OFI, et.PO, ET.COMBO, ET.COLPZA, MIN(ET.QTY) AS QTY, SUM(ET.KGS) AS KGS,ET.TELA,
                ft.descripcion AS FAMTEL, BB.AR_CDESCRI AS DESTEL, VO.ESTCLI, 
				(SELECT _XS    FROM VIEW_RECTILINEOS_OFI  AS OO  WHERE OO.OFI = ET.OFI AND OO.UBI = ET.UBI AND OO.TELA = ET.TELA) AS [' + @T0 + '],
				(SELECT _S     FROM VIEW_RECTILINEOS_OFI  AS OO  WHERE OO.OFI = ET.OFI AND OO.UBI = ET.UBI AND OO.TELA = ET.TELA) AS [' + @T1 + '],
				(SELECT _M     FROM VIEW_RECTILINEOS_OFI  AS OO  WHERE OO.OFI = ET.OFI AND OO.UBI = ET.UBI AND OO.TELA = ET.TELA) AS [' + @T2 + '],
				(SELECT _L     FROM VIEW_RECTILINEOS_OFI  AS OO  WHERE OO.OFI = ET.OFI AND OO.UBI = ET.UBI AND OO.TELA = ET.TELA) AS [' + @T3 + '],
				(SELECT _XL    FROM VIEW_RECTILINEOS_OFI  AS OO  WHERE OO.OFI = ET.OFI AND OO.UBI = ET.UBI AND OO.TELA = ET.TELA) AS [' + @T4 + '],
				(SELECT _XXL   FROM VIEW_RECTILINEOS_OFI  AS OO  WHERE OO.OFI = ET.OFI AND OO.UBI = ET.UBI AND OO.TELA = ET.TELA) AS [' + @T5 + '],
				(SELECT _3XL   FROM VIEW_RECTILINEOS_OFI  AS OO  WHERE OO.OFI = ET.OFI AND OO.UBI = ET.UBI AND OO.TELA = ET.TELA) AS [' + @T6 + '],
				(SELECT _4XL   FROM VIEW_RECTILINEOS_OFI  AS OO  WHERE OO.OFI = ET.OFI AND OO.UBI = ET.UBI AND OO.TELA = ET.TELA) AS [' + @T7 + '],
				(SELECT _5XL   FROM VIEW_RECTILINEOS_OFI  AS OO  WHERE OO.OFI = ET.OFI AND OO.UBI = ET.UBI AND OO.TELA = ET.TELA) AS [' + @T8 + '],
				(SELECT _6XL   FROM VIEW_RECTILINEOS_OFI  AS OO  WHERE OO.OFI = ET.OFI AND OO.UBI = ET.UBI AND OO.TELA = ET.TELA) AS [' + @T9 + '], et.ubi, et.tela
         FROM EXPLOSION_TELA AS et
              INNER JOIN FAMTELAS AS FT ON LEFT(FT.CORREL, 2) = LEFT(et.crudo, 2)
              INNER JOIN ETC AS EE ON ET.ETC = EE.CODETC
			  INNER JOIN VIEW_OFIS AS VO ON VO.OFI = ET.OFI
              INNER JOIN RSFACCAR..AL0001ARTI AS bb ON AR_CCODIGO COLLATE SQL_Latin1_General_CP1_CI_AI = ET.tela
        WHERE ET.OFI = ' + @OFI + '               AND ee.codtip = '+ '''T'''+ '
		GROUP BY ET.OFI, PO,UBI, COMBO, TELA,ft.descripcion , AR_CDESCRI, ET.COLPZA, ET.ETC, VO.ESTCLI order by et.ubi,et.tela')

--  ET.UBI, 
	--	SELECT top 1 T0,T1,T2,T3,T4,T5,T6,T7,T8,T9 FROM [PO-DETA] PD INNER JOIN POS PP ON PP.PO = PD.PO where ofi = '00009507'
	--	SELECT * FROM VIEW_OFIS   WHERE OFI =  '00009507' ORDER BY UBI, TELA


	
				/*, 
				(SELECT (CONCAT(DES01+' ' , ISNULL(DES02, ''),' ' , ISNULL(DES03,''),' ' , 
				ISNULL(DES04,''), ' ', ISNULL(DES05,''), ' ', ISNULL(DES06,''), ' ',
				ISNULL(DES07,''), ' ', ISNULL(DES08,''), ' ', ISNULL(DES09,''), ' ',
				ISNULL(DES10,''), ' ', ISNULL(DES11,''), ' ', ISNULL(DES12,''), ' ', 
				ISNULL(DES13,''), ' ', ISNULL(DES14,'') ) )
				FROM ETC AS CCC WHERE ET.ETC = CCC.CODETC) AS PZAS

				AS SELECT top 1 T0 FROM [PO-DETA] AS PP where PP.ofi = ET.PO
				AS SELECT top 1 T1 FROM [PO-DETA] AS PP where PP.ofi = ET.PO
				AS SELECT top 1 T2 FROM [PO-DETA] AS PP where PP.ofi = ET.PO
				AS SELECT top 1 T3 FROM [PO-DETA] AS PP where PP.ofi = ET.PO
				AS SELECT top 1 T4 FROM [PO-DETA] AS PP where PP.ofi = ET.PO
				AS SELECT top 1 T5 FROM [PO-DETA] AS PP where PP.ofi = ET.PO
				AS SELECT top 1 T6 FROM [PO-DETA] AS PP where PP.ofi = ET.PO
				AS SELECT top 1 T7 FROM [PO-DETA] AS PP where PP.ofi = ET.PO
				AS SELECT top 1 T8 FROM [PO-DETA] AS PP where PP.ofi = ET.PO
				AS SELECT top 1 T9 FROM [PO-DETA] AS PP where PP.ofi = ET.PO


                */
                      