USE MODELADOR
GO

--DROP TABLE [SERVICAB]
GO
CREATE TABLE [dbo].[SERVICAB](
	[NUMORD]	char(13) NOT NULL  PRIMARY KEY,
	[TIPSER]	CHAR(5)  NOT NULL DEFAULT '',
	[RUC]		CHAR(11) NOT NULL DEFAULT '',
	[ATT]		VARCHAR(100)  NOT NULL DEFAULT '',
	[TIPPAG]	CHAR(2)  NOT NULL DEFAULT '',
	[CLIENTE]	CHAR(4)  NOT NULL DEFAULT '',
	[CODMON]	CHAR(2) NOT NULL DEFAULT '',
	[CLASE]		CHAR(1)  NOT NULL DEFAULT '1',   -- 1 = PLANTA, 2 = SERVICIOS EXTERNOS
	[TIPCAM]	NUMERIC(10,4) NOT NULL DEFAULT 1,
	[IMPMN]		NUMERIC (18,3) NOT NULL DEFAULT 0,
	[IMPUS]		NUMERIC (18,3) NOT NULL DEFAULT 0,
	[SITORD]	CHAR(1)NOT NULL DEFAULT '1',
	[ENTREGA]	CHAR(100) NOT NULL DEFAULT '',
	[USUARIO]	CHAR(10),
	[FECDOC]	[SMALLdatetime] DEFAULT GETDATE(),
	[FECENT]	[SMALLdatetime] DEFAULT GETDATE(),
	[FECHA]		[SMALLdatetime] DEFAULT GETDATE(),
	[ESTADO]	CHAR(1) DEFAULT 'A'
) ON [PRIMARY]


--DROP TABLE [SERVIdet]
GO
CREATE TABLE [dbo].[SERVIDET](
	 [NUMORD]	char(13) NOT NULL ,
	 [LIN]		CHAR(2)  NOT NULL DEFAULT '01',
	 [PO]		CHAR(20) NOT NULL DEFAULT '',
	 [UBI]		INT NOT NULL DEFAULT 1,
	 [CANT]		INT  NOT NULL DEFAULT 0,
	 [PREUNI]	NUMERIC (18,3) NOT NULL DEFAULT 0,
	 CONSTRAINT PK_SERVIDET PRIMARY KEY (NUMORD,LIN)
) ON [PRIMARY]

--DROP TABLE [SERVITALLA]
GO
CREATE TABLE [dbo].[SERVITALLA](
	 [NUMORD]	char(13) NOT NULL ,
	 [LIN]		CHAR(2)  NOT NULL DEFAULT '01',
	 [Q0]		INT  NOT NULL DEFAULT 0,
	 [Q1]		INT  NOT NULL DEFAULT 0,
	 [Q2]		INT  NOT NULL DEFAULT 0,
	 [Q3]		INT  NOT NULL DEFAULT 0,
	 [Q4]		INT  NOT NULL DEFAULT 0,
	 [Q5]		INT  NOT NULL DEFAULT 0,
	 [Q6]		INT  NOT NULL DEFAULT 0,
	 [Q7]		INT  NOT NULL DEFAULT 0,
	 [Q8]		INT  NOT NULL DEFAULT 0,
	 [Q9]		INT  NOT NULL DEFAULT 0,
	 CONSTRAINT PK_SERVITALLA PRIMARY KEY (NUMORD,LIN)
) ON [PRIMARY]