USE MODELADOR
GO


--DROP TABLE [SERVIdet]
GO
CREATE TABLE [dbo].[SERVIDET](
	 [NUMORD]	char(13) NOT NULL ,
	 [LIN]		CHAR(2)  NOT NULL DEFAULT '01',
	 [PO]		CHAR(20) NOT NULL DEFAULT '',
	 [UBI]		INT NOT NULL DEFAULT 1,
	 [CANT]		INT  NOT NULL DEFAULT 0,
	 CONSTRAINT PK_SERVIDET PRIMARY KEY (NUMORD,LIN)
) ON [PRIMARY]

--DROP TABLE [SERVITALLA]
GO
CREATE TABLE [dbo].[SERVITALLA](
	 [NUMORD]	char(13) NOT NULL ,
	 [LIN]		CHAR(2)  NOT NULL DEFAULT '01',
	 [Q0]		INT  NOT NULL DEFAULT 0,
	 [Q1]		INT  NOT NULL DEFAULT 0,
	 [Q2]		INT  NOT NULL DEFAULT 0,
	 [Q3]		INT  NOT NULL DEFAULT 0,
	 [Q4]		INT  NOT NULL DEFAULT 0,
	 [Q5]		INT  NOT NULL DEFAULT 0,
	 [Q6]		INT  NOT NULL DEFAULT 0,
	 [Q7]		INT  NOT NULL DEFAULT 0,
	 [Q8]		INT  NOT NULL DEFAULT 0,
	 [Q9]		INT  NOT NULL DEFAULT 0,
	 CONSTRAINT PK_SERVITALLA PRIMARY KEY (NUMORD,LIN)
) ON [PRIMARY]